version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    restart: always
    volumes:
      - .:/app
      - ./db-data:/app/data  # Bind Mount برای ذخیره دائمی دیتابیس
    expose:
      - "8000"

    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
